Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,87 +10,90 @@ jobs:
   build:
     runs-on: ubuntu-latest
     container: registry.gitlab.com/hadzhioglu/padavan-ng
-    defaults: { run: { shell: bash } }
+    defaults:
+      run:
+        shell: bash
+
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Get variables
-      run: |
-        sed -i 's|\r$||g' variables build.config
-        . <(cat variables build.config)
-        PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
-        for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
-          echo "$v=${!v}" >> $GITHUB_ENV
-        done
-
-    - name: Download sources and toolchain
-      run: |
-        git config --global --add safe.directory '*'
-        git clone --depth=1 -b "$PADAVAN_BRANCH" "$PADAVAN_REPO" padavan-ng
-        git -C padavan-ng checkout "$PADAVAN_COMMIT"
-        
-        wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C padavan-ng --zstd -xf -
-        
-        TOOLCHAIN_BIN=$(find padavan-ng/ -type d -path "*/bin" | head -n 1)
-        echo "$GITHUB_WORKSPACE/$TOOLCHAIN_BIN" >> $GITHUB_PATH
-
-    - name: Install themes
-      run: |
-        if [[ -n $PADAVAN_THEMES ]]; then
-          git clone --depth 1 -b "$PADAVAN_THEMES_BRANCH" "$PADAVAN_THEMES_REPO" themes
-          cp -r themes/common-theme themes/jquery.js padavan-ng/trunk/user/www/n56u_ribbon_fixed
-
-          for theme in $PADAVAN_THEMES; do
-            echo "Installing $theme theme"
-            cp -r "themes/$theme-theme" padavan-ng/trunk/user/www/n56u_ribbon_fixed
+      - name: Get variables
+        run: |
+          sed -i 's|\r$||g' variables build.config
+          . <(cat variables build.config)
+          PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
+          for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
+            echo "$v=${!v}" >> $GITHUB_ENV
           done
-        fi
 
-    - name: Run custom pre-build script
-      run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'
+      - name: Download sources and toolchain
+        run: |
+          git config --global --add safe.directory '*'
+          git clone --depth=1 -b "$PADAVAN_BRANCH" "$PADAVAN_REPO" padavan-ng
+          git -C padavan-ng checkout "$PADAVAN_COMMIT"
+          
+          wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C padavan-ng --zstd -xf -
+          
+          TOOLCHAIN_BIN=$(find padavan-ng/ -type d -path "*/bin" | head -n 1)
+          echo "$GITHUB_WORKSPACE/$TOOLCHAIN_BIN" >> $GITHUB_PATH
 
-- name: Build firmware
-      run: |
-        cp build.config padavan-ng/trunk/.config
-        cd padavan-ng/trunk
-        
-        # Полный сброс и пересборка конфига BusyBox под новые флаги
-        make -C user/busybox distclean || true
-        rm -f user/busybox/busybox-1.37.0/.config
-        
-        ./build_firmware.sh
+      - name: Install themes
+        run: |
+          if [[ -n $PADAVAN_THEMES ]]; then
+            git clone --depth 1 -b "$PADAVAN_THEMES_BRANCH" "$PADAVAN_THEMES_REPO" themes
+            cp -r themes/common-theme themes/jquery.js padavan-ng/trunk/user/www/n56u_ribbon_fixed
 
-        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
-                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
-        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
-        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
+            for theme in $PADAVAN_THEMES; do
+              echo "Installing $theme theme"
+              cp -r "themes/$theme-theme" padavan-ng/trunk/user/www/n56u_ribbon_fixed
+            done
+          fi
 
-    - name: Run custom post-build script
-      run: '[[ -f post-build.sh ]] && . post-build.sh || :'
+      - name: Run custom pre-build script
+        run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'
 
-    - name: Prepare artifacts
-      run: |
-        cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
-        echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
+      - name: Build firmware
+        run: |
+          cp build.config padavan-ng/trunk/.config
+          cd padavan-ng/trunk
+          
+          # Полный сброс BusyBox под конфиг без USB/IPv6
+          make -C user/busybox distclean || true
+          rm -f user/busybox/busybox-*/.config
+          
+          ./build_firmware.sh
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: padavan-ng_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
-        retention-days: 7
-        path: |
-          ${{ env.FW_FILE_NAME }}
-          build.config
+          FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
+                          -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
+          [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
+          echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
 
-    - name: Check firmware size
-      run: |
-        partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
-        max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
-        fw_size="$(stat -c %s "$FW_FILE_NAME")"
+      - name: Run custom post-build script
+        run: '[[ -f post-build.sh ]] && . post-build.sh || :'
 
-        if ((fw_size > max_fw_size)); then
-          fw_size_fmtd="$(numfmt --grouping "$fw_size") bytes"
-          max_fw_size_fmtd="$(numfmt --grouping "$max_fw_size") bytes"
-          echo "Firmware size ($fw_size_fmtd) exceeds max size ($max_fw_size_fmtd) for your target device"
-          exit 1
-        fi
+      - name: Prepare artifacts
+        run: |
+          cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
+          echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: padavan-ng_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
+          retention-days: 7
+          path: |
+            ${{ env.FW_FILE_NAME }}
+            build.config
+
+      - name: Check firmware size
+        run: |
+          partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
+          max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
+          fw_size="$(stat -c %s "$FW_FILE_NAME")"
+
+          if ((fw_size > max_fw_size)); then
+            fw_size_fmtd="$(numfmt --grouping "$fw_size") bytes"
+            max_fw_size_fmtd="$(numfmt --grouping "$max_fw_size") bytes"
+            echo "Firmware size ($fw_size_fmtd) exceeds max size ($max_fw_size_fmtd) for your target device"
+            exit 1
+          fi
